### ISSUE TITLE
Angulartics Tag Manager + Events from third party libraries to set a custom dimension

### ISSUE THREAD

**Issue by kennsippell** [angulartics/angulartics-google-tag-manager#20]
I am using Angulartics with the popular A/B testing framework, Optimizely.  I am following their guide to [integrate with tag manager](https://help.optimizely.com/Integrate_Other_Platforms/Implementing_Optimizely_with_Google_Tag_Manager), and have the custom dimension events firing. 

When I go to test the configuration through Google Analytics Debugger, I see:

> Running command: ga("send", "event", "Optimizely", "Assigned To Campaign", {nonInteraction: true, dimension3: "League(8248719035):In_Game_Stats_Rank(8249355026):treatment"})
> analytics_debug.js:10 Command ignored. Unknown target: undefined

I think the problem is that it is missing the tracker name. `ga("gtm6.send", ....)`. 

I'm hoping this is a common problem that will happen any time you integrate third party tag manager tools with Angulartics. Is there some established guidance to help these two play together? If not, I can provide some more info and I'd love some help to figure out a solution.

**Comment by DanWilkerson** [comment]
The issue you're running in to is a result of some design decisions the GTM team made when integrating GA with GTM. That guide assumes you're using a "named" tracker (although your name is just "blank", that counts as a name). It's not an Angulartics issue, it's a GTM issue.

Unfortunately, GTM doesn't support adding commands between the standard GA commands like Optimizely wants you to do, hence the guide they have instructing you to create a custom HTML snippet instead.

There's really no fix for this right now; the only "option" is to configure all your GA tags in GTM to use that "named" tracker, which you [don't want to do, because it will totally bork a lot of your data collection](https://www.simoahava.com/gtm-tips/be-careful-with-the-tracker-name-setting/).

The only actual fix is to spy on the GA global and conditionally inject the Optimizely command after the ga('create', ...) command, which is trickier than it sounds.
